project_id = "irraxbjzwyetwicidqdv"

[functions.training-chat]
verify_jwt = false

[functions.evaluate-session]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

[functions.speak]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.send-invite]
verify_jwt = false

[functions.check-invite]
verify_jwt = false
